import math
import random


class Actions:

    def __init__(self, tama_obj):
        self.tama_obj = tama_obj

    def play(self, time=8):
        if self.tama_obj.get_hp() > 20 and self.tama_obj.get_happiness() > 5 and self.tama_obj.get_saturation() < 85:
            self.tama_obj.excite(time * 2)
            self.tama_obj.verdrecken(time)
            self.tama_obj.starve(time)
            print('Yippie, let us play!')
            print(f'Satisfaction rose by {time * 2}, hygiene and saturation decreased by {time}.')
            if random.randint(0, 8) == random.randint(0, 8):
                self.tama_obj.hurt(time * 2)
                self.tama_obj.emotion_sad(time * 3)
                print('Ahh I hurt myself :(')
                print(f'Happiness decreased by {time * 3} and health points by {time * 2} due to injury.')
        else:
            print('Lass mich in ruhe du Schwein!')

    def status(self):
        print(f'managotchi Status:')
        print(f'Name: {self.tama_obj.get_name()}, Age: {self.tama_obj.get_age()},')
        print(f'Mana: {self.tama_obj.sense_mana()}/{self.tama_obj.max_mana}')
        print(f'HP: {self.tama_obj.get_hp()}')
        print(f'Saturation: {self.tama_obj.get_saturation()}, Hygiene: {self.tama_obj.get_hygiene()}')
        print(f'Happiness: {self.tama_obj.get_happiness()}, Entertainment: {self.tama_obj.get_entertained()}')

    def rename(self, new_name):
        self.tama_obj.set_name(new_name)
        print(
            f"Name was changed to {new_name}, but it might take some time before your managotchi reacts to {new_name}.")

    def rest(self, time=1):
        if self.tama_obj.hp < 100:
            self.tama_obj.heal(5 * time)
            self.tama_obj.mana += (2 * time)
            self.tama_obj.pass_time(time - 1)
            print('ZzzZZZzzzzzZZzzzz')
            print(f'Health points regenerated by {5 * time} and Mana points by {2 * time}')
        else:
            print("I don't want to.")

    def cast_spell(self):
        number = str(input(
            'Please choose a spell. [F]ireball, [H]adoken, Har har [I]nfigare, [G]etsuga Tensho, [R]asengan, [Ge]nkidama').lower())
        match number:
            case 'f':
                if self.tama_obj.use_mana(1):
                    print('Fireball!')
                else:
                    print('Arg!')
            case 'h':
                if self.tama_obj.use_mana(1):
                    print('Hadoken!')
                else:
                    print('Arg!')
            case 'i':
                if self.tama_obj.use_mana(5):
                    print('Har har infigare!')
                else:
                    print('Stop that! Are you stupid?')
            case 'g':
                if self.tama_obj.use_mana(4):
                    print('Getsuga Tensho!')
                else:
                    print('Aaaarg!')
            case 'ge':
                if self.tama_obj.use_mana(self.tama_obj.max_mana):
                    print('Genkidama!')
                else:
                    print('Why!?:(')
            case 'r':
                if self.tama_obj.use_mana(4):
                    print('Rasengan!')
                else:
                    print('Aaaarg!')

    def spa(self, time=1):
        self.rest(2 * time)
        self.tama_obj.clean(time)
        self.tama_obj.heal(time * 10)
        self.tama_obj.pass_time(time - 1)
        print('Ahh, that was ~gooood.')

    def meditate(self, time=1):
        self.tama_obj.pass_time(math.ceil(time / 2))
        self.tama_obj.gain_mana(time)
        print('Ohmmm')

    def first_aid(self, intensity=1):
        self.tama_obj.heal(intensity * 25)
        print('Good thing we have out first aid kit')

    def eat(self):
        if self.tama_obj.feed():
            print('Nom nom nom')
        else:
            print('Uff ich bin satt.')

    def train(self, time=1):
        self.tama_obj.max_mana += time
        self.tama_obj.gain_mana(time * 5)
        self.tama_obj.pass_time(time - 1)
        print(f'While training you gained {5 * time} mana and raised your mana capacity by {time}')
        if self.tama_obj.max_mana >= 180:
            print('Pitiful mortal, now I THE GREAT BOB AM FREE')
            exit()
        else:
            print('I will slowly unravel the mysteries of the arcane.')

    def pass_time(self, time=1):
        self.tama_obj.pass_time(time)

    def play_dice(self):
        while True:
            user_ans = (input('You wanna play dice? Who has the higher number? [R]oll the dice or [Q]uit.')).lower()
            match user_ans:
                case 'r':
                    tama_roll = random.randint(1, 6)
                    user_roll = random.randint(1, 6)
                    print(f'You rolled a {user_roll} and I rolled a {tama_roll}')
                    if tama_roll > user_roll:
                        print('I win!')
                        self.tama_obj.emotion_happy(1)
                        self.tama_obj.pass_time(1)
                    elif tama_roll < user_roll:
                        print('You win!')
                        self.tama_obj.emotion_sad(1)
                        self.tama_obj.pass_time(1)
                    else:
                        print('Ha! Oddball.')
                        self.tama_obj.pass_time(1)
                case 'q':
                    break
